# -*- coding: utf-8 -*-
"""arbol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNNODGYrMH-PdQOHzvr6XQkpYus2mjrK
"""



import requests
import pandas as pd

url = 'https://raw.githubusercontent.com/Fernoguez/EEG/main/DM.csv'
file_name = 'DM.csv'

# Download the file
response = requests.get(url)
with open(file_name, 'wb') as f:
    f.write(response.content)

print(f"File '{file_name}' downloaded successfully.")

df = pd.read_csv('DM.csv')

print("First 5 rows of the DataFrame:")
display(df.head())

print(df.info())

"""Basándome en los nombres de las columnas y el contexto de los electroencefalogramas (EEG), aquí te presento una descripción de lo que cada columna podría representar:

*   **`Grupo`**: Probablemente indica el grupo al que pertenece el participante. Esto podría ser un grupo de control, un grupo experimental, o diferentes condiciones dentro de un estudio.
*   **`Participante`**: Un identificador único para cada individuo que participó en el estudio. Por ejemplo, 'EMV', 'RCH', 'LDC', etc.
*   **`Minuto`**: El minuto específico en el que se tomó la medición. Esto sugiere que los datos se recopilaron a lo largo del tiempo, quizás en intervalos de un minuto.
*   **`C3`, `C4`, `P3`, `P4`, `O1`, `O2`, `F3`, `F4`, `F7`, `F8`, `T7`, `T8`**: Estas son denominaciones estándar de electrodos utilizadas en el sistema internacional 10-20 para la colocación de electrodos EEG en el cuero cabelludo. Cada una representa la actividad eléctrica cerebral medida en una ubicación específica:
    *   `C3`, `C4`: Regiones centrales del cerebro.
    *   `P3`, `P4`: Regiones parietales.
    *   `O1`, `O2`: Regiones occipitales (visuales).
    *   `F3`, `F4`: Regiones frontales.
    *   `F7`, `F8`: Regiones fronto-temporales laterales.
    *   `T7`, `T8`: Regiones temporales.
    Los valores en estas columnas probablemente representan alguna métrica de la señal EEG en esos puntos, como la potencia de una banda de frecuencia (ej. Alfa, Beta, Theta) o una medida de amplitud.
*   **`AF7`, `AF8`, `FP1`, `FP2`**: También son ubicaciones de electrodos:
    *   `AF7`, `AF8`: Regiones ántero-frontales.
    *   `FP1`, `FP2`: Regiones fronto-polares.
*   **`FC5`, `FC6`, `FC1`, `FC2`**: Otras ubicaciones de electrodos, representando regiones fronto-centrales.
*   **`CP5`, `CP6`, `CP1`, `CP2`**: Ubicaciones de electrodos, representando regiones centro-parietales.
*   **`PO3`, `PO4`, `POZ`**: Ubicaciones de electrodos, representando regiones parieto-occipitales. `POZ` es una ubicación en la línea media.
*   **`FCZ`, `CZ`, `PZ`**: Ubicaciones de electrodos en la línea media:
    *   `FCZ`: Fronto-central medio.
    *   `CZ`: Central medio.
    *   `PZ`: Parietal medio.
*   **`FZZ`, `ROZ`**: Estas no son ubicaciones estándar en el sistema 10-20 y podrían ser ubicaciones personalizadas o errores tipográficos. Si 'ROZ' es 'OZ', sería una ubicación occipital en la línea media. 'FZZ' podría ser 'FZ', que es frontal medio.
*   **`ROG`**: Podría ser una abreviatura para 'Right Orbital Gyrus' o alguna otra región específica, o quizás un artefacto o una métrica derivada. Necesitaría más contexto para confirmar.
*   **`T3`**: También es una ubicación de electrodo (Temporal Izquierda).

En resumen, la mayoría de las columnas con nombres como `C3`, `F4`, etc., representan lecturas de la actividad cerebral de diferentes electrodos EEG a lo largo del tiempo y para diferentes participantes/grupos.
"""