# -*- coding: utf-8 -*-
"""RF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxNxhVcNpWtRZXGmkDHfp446KKS_PauF
"""



import pandas as pd
import requests

url = 'https://raw.githubusercontent.com/Fernoguez/EEG/main/DM.csv'
response = requests.get(url)

# Guardar el contenido en un archivo local
with open('DM.csv', 'wb') as f:
    f.write(response.content)

print("Archivo 'DM.csv' descargado exitosamente.")

df = pd.read_csv('DM.csv')

print("Primeras 5 filas del DataFrame:")
display(df.head())

# Descomprimir el archivo ZIP
!unzip "/content/Documento de_.zip" -d /content/unzipped_data

# Listar los contenidos de la carpeta descomprimida
!ls /content/unzipped_data

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.datasets import load_iris

# 1. Cargar un conjunto de datos de ejemplo (Iris dataset)
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target)

print("Primeras 5 filas de las características (X):")
display(X.head())
print("Primeras 5 filas de las etiquetas (y):")
display(y.head())

# 2. Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Tamaño del conjunto de entrenamiento: {X_train.shape[0]}")
print(f"Tamaño del conjunto de prueba: {X_test.shape[0]}")

# 3. Inicializar y entrenar el modelo Random Forest Classifier
# n_estimators: número de árboles en el bosque
# random_state: para reproducibilidad de los resultados
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("Modelo Random Forest entrenado exitosamente.")

# 4. Realizar predicciones en el conjunto de prueba
y_pred = model.predict(X_test)

# 5. Evaluar el rendimiento del modelo
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"\nPrecisión del modelo: {accuracy:.2f}")
print("\nReporte de Clasificación:\n")
print(report)

# Opcional: Mostrar la importancia de las características
feature_importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nImportancia de las características:\n")
display(feature_importances)

"""### 1. Estadísticas Descriptivas de los Canales EEG"""

# Identificar columnas que probablemente son canales EEG (numéricas y no 'Minuto', 'Grupo Participante')
# Excluir 'Grupo Participante' y 'Minuto' si son identificadores o índices de tiempo
# Asumimos que los canales son las columnas numéricas restantes

# Seleccionar columnas numéricas que no sean 'Minuto' ni 'Grupo Participante' para el análisis
channel_columns = df.select_dtypes(include=['number']).columns.tolist()
if 'Minuto' in channel_columns:
    channel_columns.remove('Minuto')
if 'Grupo Participante' in channel_columns:
    channel_columns.remove('Grupo Participante')

eeg_channels_df = df[channel_columns]

print("Estadísticas Descriptivas para los Canales EEG:\n")
display(eeg_channels_df.describe())

"""# Análisis Preliminar de Datos de Electroencefalograma (EEG)

Este cuaderno de Jupyter/Colab presenta un análisis exploratorio inicial de datos de electroencefalograma (EEG). El objetivo es cargar los datos, obtener estadísticas descriptivas básicas de los canales EEG y visualizar las series de tiempo para una primera inspección de la señal. Este análisis sienta las bases para estudios más avanzados de procesamiento de señales EEG.

## Índice

1.  [Carga y Exploración Inicial de Datos](#carga-y-exploracion-inicial-de-datos)
2.  [Estadísticas Descriptivas de los Canales EEG](#estadisticas-descriptivas-de-los-canales-eeg)
3.  [Visualización de Series de Tiempo para Canales Seleccionados](#visualizacion-de-series-de-tiempo-para-canales-seleccionados)

## 1. Carga y Exploración Inicial de Datos

En esta sección, descargamos los datos EEG desde una URL de GitHub y los cargamos en un DataFrame de Pandas. Luego, mostramos las primeras filas para verificar que la carga se haya realizado correctamente y entender la estructura básica del dataset.

### 2. Estadísticas Descriptivas de los Canales EEG

Las estadísticas descriptivas (`describe()`) son cruciales en el análisis EEG porque nos ofrecen una visión rápida de la naturaleza de la señal en cada canal. Cada fila en la tabla de resultados significa:

*   **`count`**: Número de mediciones válidas para el canal. Útil para detectar datos faltantes.
*   **`mean` (Media)**: Valor promedio de la señal, indicando el valor central. Cambios pueden sugerir artefactos o desplazamientos.
*   **`std` (Desviación Estándar)**: Mide la variabilidad o 'ruido'. Valores altos pueden indicar artefactos o actividad intensa.
*   **`min` (Mínimo)**: Valor más bajo registrado. Ayuda a identificar picos negativos o artefactos.
*   **`25%` (Primer Cuartil o Q1)**: El 25% de los datos están por debajo de este valor.
*   **`50%` (Mediana o Q2)**: El valor central de la señal (50% de los datos son menores, 50% mayores). Es robusto a valores atípicos.
*   **`75%` (Tercer Cuartil o Q3)**: El 75% de los datos están por debajo de este valor.
*   **`max` (Máximo)**: Valor más alto registrado. Ayuda a identificar picos positivos o artefactos.

Estos valores permiten una primera inspección de la calidad de los datos y detectar posibles anomalías.

### 3. Visualización de Series de Tiempo para Canales Seleccionados

Esta visualización es fundamental para el EEG por varias razones:

*   **Detección de Artefactos**: Permite identificar visualmente artefactos comunes como movimientos oculares, contracciones musculares o ruido eléctrico, que se manifiestan como grandes desviaciones o patrones anómalos en la señal.
*   **Patrones Visuales**: Ayuda a observar patrones generales de actividad cerebral, aunque para ritmos específicos se requiere un análisis de frecuencia.
*   **Homogeneidad de la Señal**: Permite verificar si la señal es consistente a lo largo del tiempo o si hay secciones donde los datos son planos (pérdida de señal) o excesivamente ruidosos.

La inspección visual de los datos crudos es un paso crucial antes de cualquier procesamiento o análisis más complejo.

### 4. Descarga de Estadísticas Descriptivas
"""

eeg_descriptive_stats = eeg_channels_df.describe()
eeg_descriptive_stats.to_csv('eeg_descriptive_statistics.csv')
print("La tabla de estadísticas descriptivas ha sido guardada como 'eeg_descriptive_statistics.csv'.")